extensionName: hello-world
hostAddress: 127.0.0.1
hostPort: 4500
opensearchAddress: 127.0.0.1
opensearchPort: 9200
ssl.transport.enabled: true
ssl.transport.pemcert_filepath: admin.pem
ssl.transport.pemkey_filepath: admin-key.pem
ssl.transport.pemtrustedcas_filepath: root-ca.pem
ssl.transport.enforce_hostname_verification: false
path.home: /Users/steecraw/opensearch-sdk-java
